### PR TITLE
mx1.getInverse( mx2 ) replaced with mx1.copy( mx2 ).invert()

### PR DESCRIPTION
**Pull request by RemusMar**
Compatible with THREE r.123

### CODE REVIEW

**Comment by RemusMar** [comment]
Here is the latest THREE r.123 beta and the updated SEA3D in action:
https://necromanthus.com/Test/html5/testA_disco.html

**Comment by sunag** [comment]
@RemusMar Thanks... how are you?

**Comment by RemusMar** [comment]
> how are you?

We're all healthy here (UK and Romania), but the next months won't be easy for anyone.
My best wishes to you and your family.
cheers

**Comment by KarimJedda** [comment]
Sorry to jump in :) Love the project and I've been playing a bit with it lately. I would love to know where I can get the scene editors for Sea3D? All the links in the documentation seem broken :( 
I would basically like to edit objects and load them in the player however I use Blender. I can gladly write a blender plugin to sea3D exporter if it's required. 
Thank you and have a lovely year!

**Comment by ivent** [comment]
Hello guys @sunag for years I have been following your work and far it is one of the most promising 3D web projects I have ever seen, even more proud to know that they were developed by Brazilians like me, so I had a project in sea3d stopped for years that I decided reactivate during the pandemic and end, but I was sad to see that since 2016 the project was abandoned and the community and the website at poonya.com went offline, so I would like to know if the project was abandoned and if so for what reason, if I can follow my project in sea or recommend me to switch to another language, or if there is an update update, I would also like a link to download the sea3d setup that I can’t download anymore, since I would like to congratulate the team for their brilliant work and I hope they can reactivate the community.

**Comment by RemusMar** [comment]
Yes, it's a great piece of work and it should be updated.
@sunag 
We need to convert it to ES6 first of all.

**Comment by RemusMar** [comment]
@sunag 
I am trying to update SEA3D in order to work with the latest THREE beta.
We need your help here: https://github.com/mrdoob/three.js/issues/21419

**Comment by sunag** [comment]
Please try download from this link:
https://www.sino3d.app/setup/SEA3DSetup.exe

I think a good start would be to leave SEA3D Studio open source?

**Comment by sunag** [comment]
> We need to convert it to ES6 first of all.

Yes, and 'class based'.

**Comment by sunag** [comment]
Guys, thank you for your encouragement.

**Comment by wwwonka** [comment]
SEA3D Studio was the very best experience with regards to preparing and exporting 3d assets. ... Bring it back!

**Comment by ivent** [comment]
@sunag  bring it back, you guys did an incredible job and until today I haven't found anything similar and so simple to work with, if the question is investment opens a Crowdfunding campaign that we will collaborate with as much as we can, but I just wanted to say that your community is still is alive here.

**Comment by sunag** [comment]
Friends, follow this work: 
https://github.com/sunag/flow

Soon I will integrate 3d too.

**Pull request closed without merging**
